name: BirthDaySign
on:
  schedule:
    - cron: 18 8,20 * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
        
      - name: dotnetEnv
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          
      - name: build
        run: dotnet build -c Release
        
      - name: run
        run: dotnet run
        env:        
          CONF: ${{ secrets.CONF }}
        